### ISSUE TITLE
[Feature Request] Add server memory usage as a config option

### ISSUE THREAD

**Issue by This-guy-breaks-shit** [Tre5et/adaptiveview#5]
This mod is awesome and has been working great on my server, unfortunately I've had a couple of crashes due to running out of memory. Could it be possible to adjust render distance based on server memory usage?

**Comment by Tre5et** [comment]
This is certainly possible. I'm current reworking how the view distance adjusting works, and I can probably add this.

There are a few reasons however why changing view distance based on memory isn't as straight forward as changing based of MSPT. The main issue being that memory consumption is not very fast to update. This means when the view distance is adjusted, the memory used for previously loaded chunks may not be immediately freed. This drastically limits the update rate that should be used to prevent over- or undershooting memory targets.  
Also, memory is mostly a function of view distance and player count and not influenced by many other factors. After the rework, you should be able to adjust view distance based on player count, which is probably preferable in most situations.

The following isn't strictly related to this mod, but something I've learned from hosting servers myself:  
If your server is crashing due to running out of memory, there are probably different issues than just too high view distance. This seems like it's likely a memory leak caused by some mod you have (unfortunately, that's rather common). I suggest making sure all your mods are up-to-date and logging memory usage. If you see a steady increase in memory usage even with constant view distance and player count, this is likely the case, and you need to experiment with the mod set you use (or just restart your server on a schedule that prevents this from consuming too much memory).

**Comment by Tre5et** [comment]
Added memory config options in v2.0.0.
